### PR TITLE
WIP: Documentation updates

### PR DESCRIPTION
**Pull request by juddfranklin1**
I am focused solely on the documentation. I have tried to make sure that grammar is clean, procedural instructions are clearly organized, links and explanations are provided when useful, and tone is a bit more consistent.

This is still in progress, but I wanted to open the pull request so that people can tell me if I am on the right or wrong track.

### CODE REVIEW

**Comment by brammittendorff** [comment]
@juddfranklin1 If this is a work in progress I suggest putting `WIP:` in front of the PR. Many developer platforms make us of this:
https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_requests.html
https://github.com/apps/wip

**Comment by ifox** [comment]
Hi @juddfranklin1! This is great, thank you so much.

 👍 👍 👍 

I'll take some time to review this week, but it's really looking good.

**Comment by juddfranklin1** [comment]
> @juddfranklin1 If this is a work in progress I suggest putting `WIP:` in front of the PR name. Many developer platforms make us of this:
> https://docs.gitlab.com/ee/user/project/merge_requests/work_in_progress_merge_requests.html
> https://github.com/apps/wip

Excellent idea. Done.

**Comment by juddfranklin1** [comment]
I haven't figured out how to locally preview the documentation with images. I have previewed it structurally, and used the npm script to run builds of the full documentation, but does anyone have advice on getting images to render in the generated .md file?

**Comment by ifox** [comment]
@juddfranklin1 you can run `npm run dev` in the `docs` folder to serve the docs site locally.

**Comment by juddfranklin1** [comment]
> @juddfranklin1 you can run `npm run dev` in the `docs` folder to serve the docs site locally.

*facepalm*

Thank you.

**Comment by dubcanada** [comment]
One big thing I think that is missing is how to setup blocks/repeaters and the other fields and what exactly the migrations/columns that are needed.

I've been playing around with redoing some of the documentation, for personal usage. Would there be interest in this? I've been using https://github.com/saleem-hadad/larecipe to do it.

If there is maybe we could combine efforts @juddfranklin1 

Thoughts @ifox

**Comment by juddfranklin1** [comment]
@dubcanada Do you have your altered documentation in a repository? Also, are you rebuilding from scratch? It looks like LaRecipe does a lot of what the current documentation development workflow does.

**Comment by dubcanada** [comment]
@juddfranklin1 I am rebuilding it from scratch/copying in parts.

However I may not follow through with that and continue with adjusting here, I do find the current documentation a little hard to use.

**Comment by ifox** [comment]
Hi @juddfranklin1! I'm going to close this as we actually used a lot of your changes for Twill 2.0 docs. Thank you so much again for your initiative.

**Pull request closed without merging**
