### PR TITLE
fix: Disable permalink option in controller stub if module has no slugs

### PR DESCRIPTION
**Pull request by pboi20**
## Description

Reported earlier today on Discord by `@leftblank`:
> I have created a module which wasn't specified to use slugs, and clicking the Edit icon next to the title also shows an editable Permalink field, which doesn't seem to update after a save. 

This adds a check to ensure that the permalink field is hidden if the module has no slugs.

## Related Issues

—

### CODE REVIEW

**Comment by pboi20** [comment]
Not sure if this is cleaner — Another option is to handle this in the controller stub:
If the module was generated without slugs, prefill the `$indexOptions` with `'permalink' => false`

**Comment by ifox** [comment]
Would using `||` instead of `&&` be a good option?

**Comment by ifox** [comment]
Unless I'm not properly awake, I think that would allow existing users that have leveraged the permalink field without slugs enabled to continue doing so by setting their indexOptions to true. I'm afraid both approaches are somewhat of a breaking change.

**Comment by pboi20** [comment]
I believe using `||` would negate the check for `moduleHas('slugs')`, because of the default value of `'permalink' => true` in `$defaultIndexOptions`.

Curious to know what you think of handling this in the controller stub? This would make it a non-breaking change for existing projects.

**Comment by ifox** [comment]
That makes sense with our default, I thought it'd be false without looking. Let's move forward with the stub approach.

**Review by ifox — APPROVED** [review]

**Pull request merged**
