### PR TITLE
[2.x][Hotfix] Fix laravel 9 compatibility

### PR DESCRIPTION
**Pull request by haringsrob**
Laravel added singleton as a route in the last release.

As we also use that as a macro we have to introduce this breaking change.

To add to release notes:

To fix replace all:
- `Route::singleton` -> `Route::twillSingleton`

### CODE REVIEW

**Comment by haringsrob** [comment]
@ifox anything I may be missing here?

**Comment by ifox** [comment]
Nope, looking good! 

The only thing is that we're not supposed to do breaking changes on 2.x but it wouldn't make sense for it to be 3 either.

Considering the change is very simple to apply for consumers, I think this is fine to do as a minor. We'll just blame Laravel for stealing our route macro name if someone isn't happy about it 🙃

**Comment by haringsrob** [comment]
It is indeed a breaking change but required to continue to support Laravel 9. Can we message users on composer update somehow?

**Comment by haringsrob** [comment]
> Maybe overkill, but what do you think about providing a Rector rule for it? I guess we'll want it for Twill 3 anyway, so it could be nice to ship it here too.

This type of change cannot be changed with rector that easily I am afraid. It's a simple find-and-replace, we could provide an example on how to do that? But this as well seem's too much, it is/should be just  a change in routes/admin.php

**Comment by ifox** [comment]
https://gist.github.com/delenamalan/3c0d998a316031af8f0f9c0165eacc28

**Pull request closed without merging**
