### PR TITLE
[2.x] support chinese tag

### PR DESCRIPTION
**Pull request by thingasd**
## Related Issues
#1883

### CODE REVIEW

**Comment by haringsrob** [comment]
Hey @thingasd do you perhaps have an example string for this?

**Comment by thingasd** [comment]
> Hey @thingasd do you perhaps have an example string for this?

do u mean an example tag with Chinese? ”標籤” ”示範”

**Comment by haringsrob** [comment]
Just to confirm, as I am adding tests, if you have 標籤 as a tag, 標籤 should be the slug?

**Comment by haringsrob** [comment]
Because for the case below, the string should build the slug, but it is, with this implementation, just returning the same as the name:

```php            'chinesecharacters3' => [
                'string' => 'test:示@範 foo!',
                'slug' => 'test示at範-foo'
            ],
```

**Comment by haringsrob** [comment]
If we use the suggestion from https://github.com/cviebrock/eloquent-sluggable/issues/392

We get:

```php
                'string' => 'test:示@範 foo!',
                'slug' => 'test-示-範-foo-'
```

Which I believe is a better outcome. What do you think?

**Comment by thingasd** [comment]
> If we use the suggestion from [cviebrock/eloquent-sluggable#392](https://github.com/cviebrock/eloquent-sluggable/issues/392)
> 
> We get:
> 
> ```
>                 'string' => 'test:示@範 foo!',
>                 'slug' => 'test-示-範-foo-'
> ```
> 
> Which I believe is a better outcome. What do you think?
> 
> [8fcf87f](https://github.com/area17/twill/commit/8fcf87ffc582b7ec7c8a0bddca3b7c13349548a9)



> 

YES

**Pull request merged**
