### PR TITLE
The block editor now accepts a title, to customize the label on the b…

### PR DESCRIPTION
**Pull request by madsem**
The block editor now accepts a title, to customize the label on the button. If left out it falls back to 'Add Content'

### CODE REVIEW

**Comment by ifox** [comment]
That's great thanks @madsem! This can go in 1.2 though, would you mind creating another PR that merges into 1.2? You can checkout our contributions guidelines [here](https://twill.io/docs/#contribution-guide).

**Comment by madsem** [comment]
alright sorry, misread that major features go into master only :) Will create another one for 1.2

**Comment by madsem** [comment]
Added a new feature:
ModuleRepository now supports populating the Browser field type via external content coming for example from an API.

**Comment by ifox** [comment]
Thank you @madsem, merged the ability to have a custom block editor title in 7382c64c1bf09a092812ab245a3e2d1f5092fd38. However, it seems like you added some unrelated changes in this PR. Feel free to submit another one now that 1.2.2 is available.

**Pull request closed without merging**
