### PR TITLE
Add connected fields support to the Twill 3 form builder

### PR DESCRIPTION
**Pull request by joyceverheije**
## Description

This has been reported many times on Discord as missing from the new form builder. Developers were forced to use a `BladePartial` field to use the `@formConnectedField` directive or component in a Blade file. 

Now they can simply use `->connectedTo($fieldName, $fieldValues)` on a form builder field to use this functionality. Additional options are supported by a third parameter of type `array`.

### Examples

```php
Checkbox::make()->name('use_source_description'),
Wysiwyg::make()
    ->name('source_description')
    ->connectedTo('use_source_description', true),
Wysiwyg::make()
    ->name('description')
    ->connectedTo('use_source_description', false),
```

```php
Checkbox::make()->name('use_source_description'),
Wysiwyg::make()
    ->name('source_description')
    ->connectedTo('use_source_description', true, ['keepAlive' => true]),
Wysiwyg::make()
    ->name('description')
    ->connectedTo('use_source_description', false, ['keepAlive' => true]),
```

### CODE REVIEW

**Comment by Jigsaw5279** [comment]
I've literally JUST been trying to find how to do this when the notification about this PR came in..

**Review by ifox — APPROVED** [review]

**Comment by Tofandel** [comment]
There is one thing that's not possible with the `connectedTo` approach that is possible with blade and that is nested `connectedTo` for multiple dependencies

**Comment by ifox** [comment]
@Tofandel good point, could you share a Blade example?

**Comment by Tofandel** [comment]
Eg an input that shows if 2 fields have a specific value

```blade
<x-twill::formConnectedFields
    field-name="type"
    field-values="video"
>
  <x-twill::formConnectedFields
      field-name="provider"
      field-values="youtube"
  >
      <x-twill::input
          name="video_embed"
          label="Video embed"
      />
  </x-twill::formConnectedFields>
</x-twill::formConnectedFields>
```

**Pull request merged**
