### PR TITLE
Add "link" function to TipTap Wysiwyg editor

### LINKED ISSUE #1805: Cannot add Link or Text Align buttons to Tiptap WYSIWYG editor
## Description

I am trying to add a link button and a text align button to the Tiptap editor, however they are not added.

### Steps to reproduce

Add a WYSIWYG field:

```php
@formField('wysiwyg', [
    'name' => 'content',
    'label' => 'Content',
    'type' => 'tiptap',
    'toolbarOptions' => [
        'bold',
        'italic',
        'clean',
        'underline',
        'link',
        ["align" => []],
        [ 'header' => [1, 2, 3, 4, 5, 6, false] ],
        ['list' => 'ordered'], 
        ['list' => 'bullet'],
        ['script' => 'sub'],
        ['script' => 'super'],
    ],
])
```

### Expected result

These buttons should be added, as they do with the Quill editor.

### Actual result

They are not added.

### Versions

Twill version:  2.8.8
Laravel version:  9.26.1
PHP version: 8.0.11

### PR DESCRIPTION
**Pull request by johnwedgbury**
## Description

This PR enables the hyperlink feature in the TipTap WYSIWYG editor. This is currently incomplete and disabled, and the only workaround being to copy pre-formatted text from another editor like Word.

New icon has been added in the header will launch a modal to accept a link URL and the option of opening in a new page.

Screenshot 2022-07-13 at 16 18 10

This is a basic implementation but I think an essential feature for people using TipTap.

## Related Issues

Related posts reporting this issue:
https://spectrum.chat/twill/help/tiptap-wysiwyg~6adf54cf-be29-412a-b115-20fe34adf977
https://spectrum.chat/twill/feature-requests/need-hyperlinking-in-tiptap-editor~723d4cdc-9566-4055-99e7-e0409baa194e

fixes #1805

### CODE REVIEW

**Comment by johnwedgbury** [comment]
Hi @haringsrob ,

Thanks for your feedback, I have addressed those points.

Please let me know if there is anything further

**Comment by johnwedgbury** [comment]
@haringsrob sorry to nudge. Would you be able to review this if you get chance please?

**Comment by haringsrob** [comment]
Hey @johnwedgbury, we are doing a final design check then we can merge this.

**Comment by kylegoines** [comment]
Hi @johnwedgbury i am currently adding some style enhancements to your link modal, after discussing with the twill design team.
One request from the design/UX team is for the modal to display the current focused text - with the ability to update the text value in that modal.
i have attached an image of the desired modal -
Screen Shot 2022-11-15 at 3 37 10 PM

let me know if that is possible or if i can clarify anything for you :)

**Comment by haringsrob** [comment]
Thanks again all for the help, this work is ported to 3.x

https://github.com/area17/twill/pull/2080

**Pull request closed without merging**
