### PR TITLE
[2.x] Make 'Add Block' scrollable

### PR DESCRIPTION
**Pull request by domihagen**
## Description

This PR sets a max-height for the 'Add Block' Dropdown to make it scrollable.

Before:
add_block_before

After:
add_block_after

### CODE REVIEW

**Comment by haringsrob** [comment]
Hey @ifox I think this is a great improvement. Does this need to go past design?

**Comment by haringsrob** [comment]
This is related: https://github.com/area17/twill/issues/89

There were commits in the past as well

**Comment by ifox** [comment]
I'm going to close this PR as we already have a 430px max height set on the scroller element of this dropdown. A default of 270px would be too small. If you are not able to scroll this dropdown, can you please submit an issue that describes your environment? Thank you!

**Comment by ifox** [comment]
Oooh, I misinterpreted this, my bad. I would then recommend to port the configuration of the one that does scroll to the one that doesn't, not to introduce a smaller max height.

**Comment by domihagen** [comment]
@ifox PR is updated. Changed the max-height to 430px like it is for the oder Dropdown.

**Pull request merged**
