### PR TITLE
Add ability to store more data from the Google Maps API

### PR DESCRIPTION
**Pull request by sauron**
Add ability to store more data from the Google Maps API form field.

- Add documentation for the saveExtendedData parameter.
- Add examples of the returned and stored data.

### CODE REVIEW

**Comment by daun** [comment]
That's a great idea! How do you feel about saving the zoom level as well? That's usually enough for re-creating the map on the frontend later. That's of course assuming you're actually using Google Maps and not some other provider.

**Comment by sauron** [comment]
Hey @daun, the data stored for the Bounding Box, it is exactly what is displayed in the viewport.
That should be enough for basic calculations like detecting if a given lat, long is included within the selected location.
But, there is definitively room for improvement in the future.

**Pull request merged**
