### PR TITLE
Laravel 8 and PHP 8 support

### PR DESCRIPTION
**Pull request by ifox**
Once all our dependencies release a new version supporting Laravel 8, Twill 2.2 will be released.

The remaining dependencies we need an update from are:
- ~https://github.com/cartalyst/tags, where I opened a PR: https://github.com/cartalyst/tags/pull/38~
- ~https://github.com/lazychaser/laravel-nestedset, where a PR has already been opened: https://github.com/lazychaser/laravel-nestedset/pull/472.~

### CODE REVIEW

**Comment by Synalek** [comment]
@ifox What about `matthewbdaly/laravel-azure-storage`?

**Dependency tree (short):**

```
├──matthewbdaly/laravel-azure-storage ^1.3
│  └──league/flysystem-azure-blob-storage ^0.1.6
│     ├──microsoft/azure-storage-blob ^1.1
│     │  ├──microsoft/azure-storage-common ~1.5 -------------------> there is no newer version
│     │  │  ├──guzzlehttp/guzzle ~6.0 -------------------> old version
│     │  │  └──php >=5.6.0
```

**Dependency tree (full):**

```
├──matthewbdaly/laravel-azure-storage ^1.3
│  └──league/flysystem-azure-blob-storage ^0.1.6
│     ├──guzzlehttp/psr7 ^1.5
│     │  ├──php >=5.4.0
│     │  ├──psr/http-message ~1.0
│     │  │  └──php >=5.3.0
│     │  └──ralouphie/getallheaders ^2.0.5 || ^3.0.0
│     │     └──php >=5.6
│     ├──league/flysystem ^1.0
│     │  ├──ext-fileinfo *
│     │  ├──league/mime-type-detection ^1.3
│     │  │  ├──ext-fileinfo *
│     │  │  └──php ^7.2 || ^8.0
│     │  └──php ^7.2.5 || ^8.0
│     ├──microsoft/azure-storage-blob ^1.1
│     │  ├──microsoft/azure-storage-common ~1.5
│     │  │  ├──guzzlehttp/guzzle ~6.0
│     │  │  │  ├──ext-json *
│     │  │  │  ├──guzzlehttp/promises ^1.0
│     │  │  │  │  └──php >=5.5.0
│     │  │  │  ├──guzzlehttp/psr7 ^1.6.1
│     │  │  │  │  ├──php >=5.4.0
│     │  │  │  │  ├──psr/http-message ~1.0
│     │  │  │  │  │  └──php >=5.3.0
│     │  │  │  │  └──ralouphie/getallheaders ^2.0.5 || ^3.0.0
│     │  │  │  │     └──php >=5.6
│     │  │  │  ├──php >=5.5
│     │  │  │  └──symfony/polyfill-intl-idn ^1.17.0
│     │  │  │     ├──php >=5.3.3
│     │  │  │     ├──symfony/polyfill-intl-normalizer ^1.10
│     │  │  │     │  └──php >=5.3.3
│     │  │  │     ├──symfony/polyfill-php70 ^1.10
│     │  │  │     │  ├──paragonie/random_compat ~1.0|~2.0|~9.99
│     │  │  │     │  │  └──php ^7
│     │  │  │     │  └──php >=5.3.3
│     │  │  │     └──symfony/polyfill-php72 ^1.10
│     │  │  │        └──php >=5.3.3
│     │  │  └──php >=5.6.0
│     │  └──php >=5.6.0
│     └──php >=5.6
```

**Comment by ifox** [comment]
You're right. I found this issue https://github.com/Azure/azure-storage-php/issues/248 which doesn't seem like a priority in the repo. I think we need to consider moving to an optional dependency, but I assume that would mean bumping our major version as this would be a breaking change for anyone using Azure storage on Twill currently. Or we could fork Microsoft's package, but it seems like they are worried about Guzzle breaking changes themselves, so not sure if that's a good idea to undertake on our end.

**Comment by Synalek** [comment]
As a temporary solution, moving `matthewbdaly/laravel-azure-storage` to an optional dependency sounds good (on this branch or a new one). It would let people use it at least for developing.

**Comment by Fijvect** [comment]
Hello! Any updates on this pull request? Thank you

**Comment by henze-housepedia** [comment]
> Hello! Any updates on this pull request? Thank you

we are still waiting for Azure/azure-storage-php#248. I saw that they placed it on the November milestone, so this can take another 2 to 5 weeks.

In the mean time, if you absolutely require this version and do not rely on Guzzle 7 specific features: just try dropping your Guzzle Requirement, and install this branch.

**Comment by Synalek** [comment]
@ifox https://github.com/Azure/azure-storage-php/issues/248. The MR has been merged/closed. Looks like everything is ready now. How fast Twill 2.2 can be released?

**Comment by ifox** [comment]
> @ifox [Azure/azure-storage-php#248](https://github.com/Azure/azure-storage-php/issues/248). The MR has been merged/closed. Looks like everything is ready now. How fast Twill 2.2 can be released?

Finally! We still need a tagged release from them, but as soon as it's up I will be more than happy to update this PR and release.

**Comment by GraxMonzo** [comment]
@ifox They released the new version of `azure-storage-common`. I guess it's ready for update 😋

**Comment by Andreas-Halemba** [comment]
@ifox is there any chance getting a version taged to be able to update to laravel 8?

**Comment by tobemedia** [comment]
@ifox how can we help to get Twill 2.2 with Laravel 8 support to be released? Is there anything missing?

**Pull request merged**
