### PR TITLE
[3.x] #611: Document storage link.

### LINKED ISSUE #611: Storage folder symlink creation not documented
When using the local storage endpoint we need to create the storage folder symlink using the command `php artisan storage:link`. This needs to be added to the documentation.

### PR DESCRIPTION
**Pull request by haringsrob**
## Description

Mentions to use storage link

## Related Issues

fixes #611

### CODE REVIEW

**Comment by rvyhvn** [comment]
Would be great if the `storage:link` also added on the [guide page](https://twillcms.com/guides/page-builder-with-blade/index.html).

**Comment by Tofandel** [comment]
You can very easily create a PR to add it to this page

https://github.com/area17/twill/blob/3.x/docs/content/2_guides/1_page-builder-with-blade/2_installing-laravel.md?plain=1

**Comment by rvyhvn** [comment]
@Tofandel, one more thing: When I was testing Twill using the guide, the image uploads weren't working properly. I found the fix: I had to change the `APP_URL` in my `.env` file from `http://localhost` to `http://127.0.0.1:8000`. Is this a known bug or just something the documentation missed? I’m thinking about adding a note about this to the guide so others don't get stuck.

**Comment by Tofandel** [comment]
It's a common occurrence in laravel. Normally when you install and setup your env you would always be setting this even in localhost. Laravel doesn't assume your development env. Because you could be using a local apache and that would be localhost or you could be using the artisan serve command and then it's 127.0.0.1:8080.

You can add it to this doc, but I believe it's mentioned on the laravel doc itself

**Pull request merged**
