### PR TITLE
Fix rendering for nested components.

### PR DESCRIPTION
**Pull request by haringsrob**

### CODE REVIEW

**Comment by kerkness** [comment]
There are some interesting differences with how a block component acts when nested and not nested.  I've created a test block that shows dynamically created values do not populate the view when the block is nested. 

## Block Component with single input and test properties
```
<?php

namespace App\View\Components\Twill\Blocks;

use A17\Twill\Services\Forms\Fields\Wysiwyg;
use A17\Twill\Services\Forms\Form;
use A17\Twill\View\Components\Blocks\TwillBlockComponent;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Arr;


class Text extends TwillBlockComponent
{

    // Public properties defined.
    public $defined = "This is a defined property.";

    public $redefined = "This is a default value.";

    // Public properties not defined.
    public $also_content;

    // Values set or updated here do not populate nested blade template
    public function beforeRender()
    {
        // Properties set in beforeRender are not available in the view.
        $this->also_content = Arr::get($this->block, 'content');
        $this->redefined = "This is a redefined value.";
    }

    public function render(): View
    {
        $this->beforeRender();

        return view('components.twill.blocks.text', [
            'block_content' =>  Arr::get($this->block, 'content'),
        ]);
    }

    public function getForm(): Form
    {
        return Form::make([
            Wysiwyg::make()->name('text')->translatable()
        ]);
    }

}
```

## Blade template used to test output
```
<h6>$translatedInput works nested and not nested</h6>
@dump($translatedInput('text'))

<h6>$block_content passed in view() works nested and not nested</h6>
@dump($block_content)

<h6>Public property $also_content does not work when nested</h6>
@dump($also_content)

<h6>Defined public property works nested and not nested</h6>
@dump($defined)

<h6>Redefined public property does not work when nested</h6>
@dump($redefined)
```

This is a screen shot of the preview when this block is used in a nested block editor and an non nested block editor.  Top output is nested.

image

**Comment by ifox** [comment]
Thanks for sharing this @kerkness. Could you please also share how you are using that text block to nest it, so we have a fully reproducible setup?

**Comment by kerkness** [comment]
I am using another component block with a nested block editor

```
<?php

namespace App\View\Components\Twill\Blocks;

use A17\Twill\Services\Forms\Form;
use A17\Twill\Services\Forms\Fields\BlockEditor;
use A17\Twill\View\Components\Blocks\TwillBlockComponent;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Arr;

class ContentSection extends TwillBlockComponent
{
    public $background;

    public $backgroundOptions = [
        ['label' => 'Light Gray', 'value' => 'bg-gray-100'],
        ['label' => 'Med Gray', 'value' => 'bg-gray-300'],
        ['label' => 'Dark Gray', 'value' => 'bg-gray-600'],
        ['label' => 'Transparent', 'value' => 'bg-transparent'],
    ];

    public function render(): View
    {
        $this->background = Arr::get($this->block, 'content.background', '');

        return view('components.twill.blocks.section');
    }

    public function getForm(): Form
    {
        return Form::make([
            Select::make()
                ->name('background')
                ->options(Options::make(
                    collect($this->backgroundOptions)->map(function ($option) {
                        return Option::make($option['value'], $option['label']);
                    }))
                )
                ->label('Background Color')
                ->default('bg-transparent'),
            BlockEditor::make()->name('section')
        ]);
    }

}
```

Placed the previous Text block inside a ContentSection block like so
image

**Comment by kerkness** [comment]
The blade template for ContentSections is
```
<div class="{{ $background ?? '' }}">    
    <div class="container m-auto p-4">  
        {!! $renderData->renderChildren('section') !!}  
    </div>
</div>
```

**Review by ifox — APPROVED** [review]

**Pull request merged**
