### PR TITLE
Adds conditional fields docs

### PR DESCRIPTION
**Pull request by bwaltz**
## Description

Adds some docs with examples for conditional fields. Also adds a sentence about where to upload videos to in the media library, in case anyone was confused like I was.

## Related Issues

Related to #39

### CODE REVIEW

**Comment by pboi20** [comment]
@bwaltz That's great! If I may add a minor suggestion, to use the shorter blade alias for the examples : 
```
    @formConnectedFields([
        'fieldName' => 'type',
        'fieldValues' => 'video',
        'renderForBlocks' => false
    ])
        ...
    @endformConnectedFields
```

**Comment by ifox** [comment]
@pboi20 @bwaltz I pushed an update, let me know what you think! There's also yet another way to use them, actually, if you're using Laravel 7+:

```
<x-formConnectedFields fieldName="type" fieldValues"video" renderForBlocks="false">
    ...
</x-formConnectedFields>
```

Another example:

```
<x-formFieldset title="Additional fieldset">
    ...        
</x-formFieldset>
```

**Comment by pboi20** [comment]
@ifox I like the added info block for the file library!

I personally enjoy the `<x-component>` syntax and I do think that, if/when Twill drops support for Laravel < 7.x, it would be awesome to rewrite the documentation examples. I wonder if it would be desirable to have mixed examples in the docs until then.

**Comment by bwaltz** [comment]
All fine to me! Just wanted to help future users with the documentation.

**Review by pboi20 — APPROVED** [review]

**Review by ifox — APPROVED** [review]

**Comment by ifox** [comment]
> @ifox I like the added info block for the file library!
> 
> I personally enjoy the `<x-component>` syntax and I do think that, if/when Twill drops support for Laravel < 7.x, it would be awesome to rewrite the documentation examples. I wonder if it would be desirable to have mixed examples in the docs until then.

I think we could add a section that presents that different approaches, but stick with the most compatible one in examples.

**Pull request merged**
