### PR TITLE
[3.x] Update vueselect dependency to v3

### PR DESCRIPTION
**Pull request by mazeeblanke**
Update vue select to version 3.

1) Replaced the onSearch prop with the search event has using the same parameters in it's place.
2) import the css file for the vue-select

### CODE REVIEW

**Comment by tchapi** [comment]
That would close https://github.com/area17/twill/issues/626 I think, that would be really nice !

**Comment by mazeeblanke** [comment]
@ifox thank you for the feedback. I will go through it again and fix it

**Comment by haringsrob** [comment]
I think that since we are on this we can also add support for the `selectable` https://vue-select.org/guide/selectable.html#selectable-prop option.

We could take a similar array as the `options`.

**Comment by haringsrob** [comment]
Moving this onto 3.x

**Pull request merged**
