### PR TITLE
Add arabic support translation

### PR DESCRIPTION
**Pull request by shawkiIIalasy**
## Description

Add Arabic Translations 

## Related Issues

---

### CODE REVIEW

**Comment by shawkiIIalasy** [comment]
@ifox Please check

**Comment by haringsrob** [comment]
I had a quick check and seems to work fine.

I am just wondering, shouldn't it be right-to-left for Arabic?

**Comment by shawkiIIalasy** [comment]
@haringsrob Yes, it should be

**Comment by shawkiIIalasy** [comment]
@haringsrob Please check

**Comment by ifox** [comment]
Hi @shawkiIIalasy, what would you like us to check? To follow up on Rob's question, are you feeling like Twill is usable by users setting the language to Arabic even though the UI isn't necessarily ready for a right to left language? In other words, are you confortable with us merging this without doing more work on RTL support?

**Comment by shawkiIIalasy** [comment]
@ifox Yes, I think translations is more important now compareing with RTL support and even Twill is appears good and readable on Arabic, I hope that you can merge this right now, I will help you to provide full RTL support.

Twill will be great if we can finilize Full Rtl support in future.

**Comment by haringsrob** [comment]
@ifox  I guess we can merge this one? Should we clear the commits coming from master branch or is it fine?

**Pull request merged**
