### PR TITLE
Prevent multiple submit events in add and create modals

### PR DESCRIPTION
**Pull request by pboi20**
## Description

This add a simple guard clause in the `submit` handler of `ModalAdd` and `ModalCreate` components. It prevents the creation of duplicate records when double-clicking any submit button.

## Related Issues

Fixes https://github.com/area17/twill/issues/434

### CODE REVIEW

**Comment by ifox** [comment]
Great stuff @pboi20. A somewhat related issue in the creation process is the following: if you type very quickly and press enter immediately, the title (or whatever is the first field in the create modal) might not have had the time to be updated in the store before being sent through the backend.

**Comment by pboi20** [comment]
@ifox Thanks, I'll look into the title issue! Actually, I get a feeling that it could be a more generalized issue and also affect fields in the form/edit view.

**Comment by ifox** [comment]
Right, it is related to what we discussed in #777.

**Comment by pboi20** [comment]
Also https://github.com/area17/twill/issues/777, which is a different issue but effectively the same problem.

**Review by ifox — APPROVED** [review]

**Pull request merged**
