### PR TITLE
Add localization support

### PR DESCRIPTION
**Pull request by yanhao-li**
This Pull Request try to propose a way of implementing the localization on Twill, by providing several languages folders under `views/lang`.

It included three languages as example: English (as fallback), Japanese, Chinese. This PR only covered part of the entire UI for demo purpose.

Would like to hear people's thoughts about the approach I'm taking, any comments are welcomed!

---
### Some Screenshots of a Japanese UI
Login page
image

Dashboard
image

Listing page
image

Listing modal
image

### CODE REVIEW

**Comment by antonioribeiro** [comment]
I prefer to keep structure as close as Laravel's so I would put them in:

`/resources/lang/<locale>/twill.php`

And maybe export them on `twill:install` to the app root, so people can change them and add their own translations easily?

**Comment by yanhao-li** [comment]
@antonioribeiro 
Thanks, I just converted them to a single file `lang.php`, that's indeed easier to manage in the future 😄 
and I think locale is override is supported natively by Laravel itself: https://laravel.com/docs/master/localization#overriding-package-language-files

**Comment by antonioribeiro** [comment]
@yanhao-li, pasting the VueJS code we were discussing here 

``` javascript
// ------------- localization module
import Vue from 'vue'
import VueI18n from 'vue-i18n'

Vue.use(VueI18n)

// Ready translated locale messages
import messages from './messages'

// Create VueI18n instance with options
const i18n = new VueI18n({
    locale: 'en-US', // set default locale
    messages, // set locale messages
})

export default i18n

// ---------------------------------- Messages

export default {
    'en-US': {
        auth: {
            failed: 'These credentials do not match our records.',
            throttle:
                'Too many login attempts. Please try again in :seconds seconds.',
        },
        language: {
            tag: 'en-US',
            display_name: 'English',
        },
        menu: {
            encrypt: 'Encrypt',
            about: 'About',
            admin: 'Admin',
            contact: 'Contact',
        },
        messages: {
            'incident-identification': 'Identification',
            'social-fields-list': 'Social network url, email address or phone',
        }
    },
    'pt-BR': {
        auth: {
            failed:
                'Credenciais informadas n\u00e3o correspondem com nossos registros.',
            throttle:
                'Voc\u00ea realizou muitas tentativas de login. Por favor, tente novamente em :seconds segundos.',
        },
        language: {
            tag: 'pt-BR',
            display_name: 'Portugu\u00eas',
        },
        menu: {
            encrypt: 'Encriptar',
            about: 'Sobre o Tiaki',
            admin: 'Admin',
            contact: 'Contato',
        },
        messages: {
            'incident-identification': 'Identifica\u00e7\u00e3o da pessoa',
            'social-fields-list': 'Url da rede social, email ou telefone',
        },
    },
}

// ----------------------------------- Adding to your Vue instance

import VueI18NLocalizationModule from './localization/module.js'
new Vue({
    el: '#root',
    router,
    store,
    i18n: VueI18NLocalizationModule,
});

// ----------------------------------- Using localization

<p>
    {{ $t('messages.about.text_p1') }}
</p>

// ---------------------------------- Switching locale

__switchLocale(locale, event, updateUser) {
    if (!locale) {
        return false
    }

    if (event) {
        event.preventDefault()
    }

    if (typeof updateUser === 'undefined' || updateUser) {
        this.__updateUserLocale(locale)
    }

    this.locale = locale

    this.$i18n.locale = locale ? locale : 'en-US'

    moment.locale(
        helpers.extractCountryFromLocale(this.$i18n.locale),
    )
},

// ---------------------------- Helper

extractCountryFromLocale(locale) {
    return locale.substr(0, locale.indexOf('-'))
}
```

The mesages.json builder:

```  php
Artisan::command('twill:build-messages-json', function ($command) {
    file_put_contents(
        $file = resource_path('js/lang/messages.js'),
        'export default ' . app(Service::class)->getLocalizationJson()
    );

    $this->info("Localization file generated at {$file}");
})->describe('Display an inspiring quote');
```

This is the service class which reads all files and create the json:

``` php
<?php

namespace App\Services\Localization;

use File;

class Service
{
    private function extractFileName($file)
    {
        return pathinfo($file)['filename'];
    }

    public function getLocalizationJson()
    {
        return json_encode($this->localizationMessages(), JSON_PRETTY_PRINT);
    }

    private function localizationMessages()
    {
        $messages = [];

        $files = File::allFiles(resource_path() . '/lang/');

        foreach ($files as $file) {
            $messages[$file->getRelativePath()][
                $this->extractFileName($file->getBasename())
            ] = File::getRequire($file->getRealPath());
        }

        return $messages;
    }
}

```

**Comment by yanhao-li** [comment]
## Change log
- Added Localization support to most of blade files / Vue components.
  - Added two language files:  `en` (English) and `ja` (Japanese).
  - Added a view composer `A17\Twill\Http\ViewComposers\Localization` to pass the translation to FE as string.
  - Created a FE helper to handle string translate on FE.

- Different language for different user
  - Added a language select on user form.
  - Added a new `language` column on `twill_users` table to persist user's language.
  - Added a middleware `A17\Twill\Http\Middleware\Localization` to change user's language based on setting.

**Comment by yanhao-li** [comment]
New updates:

- Fixed some bugs.
- Refactored the code by using a separate `twill.locale` config for twill, and a new helper `twillTrans`
- Added Chinese and Russian support.

**Comment by agnonym** [comment]
@yanhao-li Following a discussion on Spectrum (https://spectrum.chat/twill/feature-requests/twill-localization~8df1fc23-3954-4f4d-b0fd-358872d8c1a6), what do you think of using the curved apostrophe (’) instead of standard quote in translations to avoid JS errors? (there's one escaped quote in the english language file: https://github.com/area17/twill/pull/405/files#diff-7e65abd13fc8e1dd7d12911b7962d81b)

**Comment by yanhao-li** [comment]
Hi @agnonym ,
Sorry for the late reply, I didn't check spectrum frenquently.

I just updated the encoding strategy for publisher: https://github.com/yanhao-li/twill/commit/c2b6e5aa2019d1058bf9d1b450535cad9ad17dd4

Let me know if that fix your issue, and you could directly create a PR under my fork once you finish the translation.

Thank you!

**Comment by ifox** [comment]
This has been reviewed and merged in master. Thank you so much @yanhao-li!

**Comment by GraxMonzo** [comment]
When it will be merged?

**Pull request closed without merging**
