### PR TITLE
Fix issue #693

### PR DESCRIPTION
**Pull request by ResetButton**
Details are here https://github.com/area17/twill/issues/693

### CODE REVIEW

**Comment by ifox** [comment]
Thank you so much for your contribution @ResetButton!

I'm afraid this change would be breaking depending on how this type of field has been managed in the module repository or model. Can you share how you are saving and retrieving that field?

**Comment by ResetButton** [comment]
Absolutely similar to https://twill.io/docs/#checkboxes  I touched nothing more so module repository or model is default, I just tried to use diffent MSQL field types - JSON or string and all seems to be working.
This change is only affect "checkboxes" form field.

**Comment by ifox** [comment]
> I just tried to use different MSQL field types - JSON or string and all seems to be working.

That's the thing. The intention embedded in the current implementation is that you'd use the checkboxes field with a relationship. That's why it's trying to pull a list of ids.

**Comment by ResetButton** [comment]
I rechecked docs and my project - it will always save list of ids, because we have "value" embedded in blade and we need only "keys" saved in DB to check corresponding fields.

**Comment by ifox** [comment]
Fixed in https://github.com/area17/twill/commit/736a064262bafd4c47b0562136b8a2d859c00ca0. The checkboxes field will now work with a simple text/json column and no casting, as well as with a model relationship with another model.

**Pull request closed without merging**
