### PR TITLE
Allow wysiwyg for media.

### PR DESCRIPTION
**Pull request by haringsrob**
## Description

This enables the usage of wysiwyg in media captions.

### CODE REVIEW

**Comment by sauron** [comment]
Hey @haringsrob ,
this looks amazing, thanks for the fast implementation.
Right now we are in need of using the Wysiwyg, not only for caption but also for other "extraMetadata" fields. For example **Credit**
```php
@formField('medias', [
    'with_multiple' => true,
    'label' => 'Image Grid',
    'name' => 'gallery_thumbs',
    'max' => 1,
    'withVideoUrl' => false,
    'captionMaxLength' => 200,
    'extraMetadatas' => [
        [
            'name' => 'credit',
            'label' => 'Credit',
        ],
    ],
])
 ```
 
 Do you think it is possible to extend to the `extraMetadatas` options?

**Comment by haringsrob** [comment]
Hey @sauron,

Like this? 

https://github.com/area17/twill/pull/1540/files#diff-bdb3c1f3434ec6f5aed9084880c661ce8776c89e20433028b11416917f8e2f6c

**Comment by sauron** [comment]
Exactly like that @haringsrob !!!
🙌

**Review by sauron — APPROVED** [review]
LGTM

**Review by ifox — APPROVED** [review]

**Pull request merged**
