### PR TITLE
[3.x] allow super admins to reset 2fa for other stuck users

### PR DESCRIPTION
**Pull request by YasienDwieb**
## Description

Introduces the ability for super admins to reset 2FA for other users who may get stuck and unable to login in

Admins are required to solve a challenge before disabling 2FA for other users in order to avoid doing that by mistake

### CODE REVIEW

**Comment by haringsrob** [comment]
Hey @YasienDwieb !

I checked and this works fine. However, I think we should maybe limit the ability to disable it to admins that have 2fa themself.

What are your thoughts @ifox?

**Comment by YasienDwieb** [comment]
@haringsrob @ifox I have add privilege check and 2fa check to the request validation, please check now

Thanks

**Comment by YasienDwieb** [comment]
@haringsrob @ifox I have add privilege check and 2fa check to the request validation, please check now

Thanks

**Comment by AndreSchwarzer** [comment]
IMHO the admin should also confirm the action by reentering his own password since it's a very sensitive action.

https://laravel.com/docs/9.x/authentication#password-confirmation

https://laracasts.com/series/whats-new-in-laravel-6/episodes/5

**Comment by YasienDwieb** [comment]
@AndreSchwarzer I don't think we would need this, thinking about doing the same on AWS for example you will not be required to do so as you have already passed through all required authentication/authorization steps

**Comment by haringsrob** [comment]
I can finalize and merge this once #1360 is done

- [ ] Replace the @formField with the new components.

**Comment by haringsrob** [comment]
Hey @YasienDwieb,

This is now fine, I will merge it soon.

I also included some small bug fixes that I myself introduced (just in case you wonder about the non related changes).

**Pull request merged**
