### PR TITLE
Regression fixes for capsules.

### PR DESCRIPTION
**Pull request by haringsrob**
## Description

Fixes some small regressions.

I don't know how to trigger 'getModelRepository' so I cannot test that update. If someone can give me a config to get in that method I will double-check it.

### CODE REVIEW

**Comment by sauron** [comment]
> ## Description
> Fixes some small regressions.
> 
> I don't know how to trigger 'getModelRepository' so I cannot test that update. If someone can give me a config to get in that method I will double-check it.

Hey @haringsrob, You mean the `config/twill.php` file?

**Comment by ifox** [comment]
> > ## Description
> > Fixes some small regressions.
> > I don't know how to trigger 'getModelRepository' so I cannot test that update. If someone can give me a config to get in that method I will double-check it.
> 
> Hey @haringsrob, You mean the `config/twill.php` file?

I think he means a Twill overall configuration, as is a module or capsule and other needed blocks or config to be able to get into this code path.

**Comment by haringsrob** [comment]
Yes I know how to trigger getModelRepository with a Model, but not really how to trigger it with a Repository.

**Comment by ifox** [comment]
@haringsrob to trigger it, you need to preview a module that is using the `$browsers` array on its repository. It will trigger `hydrateBrowser` which will itself trigger this code path.

**Comment by haringsrob** [comment]
I double checked and this should be fine. The previous code only called this by model.

**Review by ifox — APPROVED** [review]

**Pull request merged**
