### PR TITLE
 Add PHPDoc (docblocks) with param and return types to all PHP methods and classes

### PR DESCRIPTION
**Pull request by stevanpavlovic**
This is related to #295. I've added the docblocks to all methods and classes. What I am missing in most of the places are method descriptions. So what I did is that I only added annotations `@param` and `@return`. Adding those method descriptions is a huge procedure and I need a lot of time to do that since I would basically have to briefly explain the whole systems' functionality. I am not giving up on that, I am just postponing that.

But first I would really love that we merge this one. I would also like to hear from you guys about these changes.

### CODE REVIEW

**Comment by yusufkandemir** [comment]
I think it's so much better to use type declarations instead of PHP doc blocks. It improves safety and decreases verbosity.

**Comment by stevanpavlovic** [comment]
@yusufkandemir I agree, but for now, that could be really risky for the implementation. I wanted to prepare everything for doing strict type hinting because a lot of untested stuff could break to invalid type hinting. This way, we will have everything implicitly described so we can do the typehinting in a more "secure" way.

**Comment by yusufkandemir** [comment]
@stevanpavlovic I agree with that. Refactoring is best when done progressively.

**Comment by ifox** [comment]
Merged in 4f80c83d and reviewed in 6f4e9c92. Thank you so much @stevanpavlovic!

**Pull request closed without merging**
